Nm_erro = {
  "lang_jscr_dcml" : "عشاریہ",
  "lang_jscr_decm" : "لمحھے  کا دسواں حصہ",
  "lang_jscr_hour" : "گھنٹہ",
  "lang_jscr_iday" : "دن",
  "lang_jscr_intg" : "عداد صحیح اور/انٹیجرز اینڈ",
  "lang_jscr_ivcr" : "غلط اُدھار کارڈ نمبر/ان ویلڈ ایڈینٹی کارڈ نمبر",
  "lang_jscr_ivdt" : "غلط ڈیٹا/ان ویلڈ ڈیٹا",
  "lang_jscr_ivem" : "غلط ای میل/ان ویلڈ ای میل",
  "lang_jscr_ivnb" : "غلط عدد صحیح /ان ویلڈ انٹیجرز",
  "lang_jscr_ivtm" : "غلط وقت/ ان ویلڈ ٹائیم",
  "lang_jscr_ivv2" : "غلط ڈیٹا/ان ویلڈ ڈیٹا",
  "lang_jscr_ivvl" : "غلط عشاریہ/ان ویلڈ ڈیسمل",
  "lang_jscr_maxm" : "حد غایت/مقیسکم",
  "lang_jscr_maxm_date" : "حد غایت تاریخ/ مقیسکم ڈیٹ",
  "lang_jscr_minm" : "کَم سے کَم/قلیل",
  "lang_jscr_minm_date" : "قلیل تاریخ/ مینمیم ڈیٹ",
  "lang_jscr_mint" : "منٹ",
  "lang_jscr_mnth" : "مہینہ",
  "lang_jscr_msfr" : "فارم پر نام ہونا ضروری ہے",
  "lang_jscr_mslg" : "لوگن موجود نہی ہے/ لاگن میسنگ",
  "lang_jscr_msob" : "اس فارم کے  آبجیکٹ  پر نام  ہونا ضروری ہے",
  "lang_jscr_mxdg" : "عداد کی تعداد توقع  سے تجاوز کر رہی ہے",
  "lang_jscr_mxvl" : "حد غایت  لمبائی  تجاوز کر رہی ہے",
  "lang_jscr_nnum" : "فیلڈ میں نمبر ڈلتے ہیں",
  "lang_jscr_nvlf" : "علامت منفی  قیمت کی بائيں طرف ہونا ضروری ہے",
  "lang_jscr_reqr" : "فیلڈ ضرورت ہے/رکیویرڈ فیلڈ",
  "lang_jscr_secd" : "لمہے",
  "lang_jscr_wfix" : "کیا آپ درست کرنا چاہتے ہیں؟"
}
