Nm_erro = {
  "lang_jscr_dcml" : "שבר עשרוני",
  "lang_jscr_decm" : "עשירית השנייה",
  "lang_jscr_hour" : "שעה",
  "lang_jscr_iday" : "יום",
  "lang_jscr_intg" : "מספר שלם ו",
  "lang_jscr_ivcr" : "מספר כרטיס אשראי שגוי",
  "lang_jscr_ivdt" : "נתונים שגויים",
  "lang_jscr_ivem" : "דואר אלקטרוני שגוי",
  "lang_jscr_ivnb" : "מספר שלם שגוי",
  "lang_jscr_ivtm" : "זמן שגוי",
  "lang_jscr_ivv2" : "שבר עשרוני שגוי",
  "lang_jscr_ivvl" : "שבר עשרוני שגוי",
  "lang_jscr_maxm" : "מקסימום",
  "lang_jscr_maxm_date" : "תאריך מקסימלי",
  "lang_jscr_minm" : "מינימום",
  "lang_jscr_minm_date" : "תאריך מינימלי",
  "lang_jscr_mint" : "דקות",
  "lang_jscr_mnth" : "חודש",
  "lang_jscr_msfr" : "הטופש הזאת חייבת להכיך שם",
  "lang_jscr_mslg" : "חסרה התחברות",
  "lang_jscr_msob" : "הטופס הזאת חייבת להכיל שם",
  "lang_jscr_mxdg" : "כמות הספרות חרגה את הצפוי",
  "lang_jscr_mxvl" : "אורך מקסימלי חורגה",
  "lang_jscr_nnum" : "השדה הזאת מספרי",
  "lang_jscr_nvlf" : "סימן השלילי חייבת להיות בצד השמאלי של הערך",
  "lang_jscr_reqr" : "השדה הזאת חייבת",
  "lang_jscr_secd" : "שניות",
  "lang_jscr_wfix" : "-אתה רוצה לתקן?"
}
