Nm_erro = {
  "lang_jscr_dcml" : "দশমিক",
  "lang_jscr_decm" : "একটি মুহুর্তের এক দশমাংশ",
  "lang_jscr_hour" : "ঘন্টা",
  "lang_jscr_iday" : "দিন",
  "lang_jscr_intg" : "পূর্ণসংখ্যা এবং",
  "lang_jscr_ivcr" : "অসিদ্ধ ক্রেডিট কার্ড সংখ্যা",
  "lang_jscr_ivdt" : "অসিদ্ধ্ তথ্য",
  "lang_jscr_ivem" : "অসিদ্ধ ইমেইল",
  "lang_jscr_ivnb" : "অসিদ্ধ পূর্ণসংখ্যা",
  "lang_jscr_ivtm" : "অসিদ্ধ সময়",
  "lang_jscr_ivv2" : "অসিদ্ধ তথ্য",
  "lang_jscr_ivvl" : "অসিদ্ধ দশমিক",
  "lang_jscr_maxm" : "সর্বাপেক্ষ্যা",
  "lang_jscr_maxm_date" : "সর্বাপেক্ষা তারিখ",
  "lang_jscr_minm" : "সর্বনিম্ন/ন্যুনতম",
  "lang_jscr_minm_date" : "ন্যুনতম  তারিখ",
  "lang_jscr_mint" : "মিনিট, বিবরণ",
  "lang_jscr_mnth" : "মাস",
  "lang_jscr_msfr" : "ফর্ম টির একটি নাম থাকা আবশ্যক",
  "lang_jscr_mslg" : "লগিন নেই",
  "lang_jscr_msob" : "ফর্ম বস্তু টির একটি নাম থাকা আবশ্যক",
  "lang_jscr_mxdg" : "রাশির পরিমান প্রত্যাশিত রাশি অতিক্রম করেছে",
  "lang_jscr_mxvl" : "সর্বাপেক্ষা দৈর্ঘ্য অতিক্রম করেছে",
  "lang_jscr_nnum" : "ক্ষেত্রটি সংখ্যাসূচক",
  "lang_jscr_nvlf" : "ঋণাত্মক চিন্হটি মূল্যের বাম দিকে থাকা বাধ্যতামূলক",
  "lang_jscr_reqr" : "ক্ষেত্রটি আবশ্যক",
  "lang_jscr_secd" : "মুহূর্ত, দ্বিতীয়",
  "lang_jscr_wfix" : "আপনি কি সংশোধন করতে চান?"
}
